-- Kilax application tables. Run this in Supabase SQL editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  email text,
  avatar_url text,
  role text not null default 'user',
  subscription text not null default 'free',
  subscription_start_date date,
  subscription_expiry_date date,
  trial_status text not null default 'inactive',
  trial_started_at timestamptz,
  trial_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  plan text,
  plan_id uuid,
  subscription_type text not null default 'premium',
  payment_method text,
  status text not null default 'active',
  start_date date,
  expiry_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  reference uuid unique,
  status text,
  amount numeric,
  currency text,
  provider text,
  provider_transaction_id text,
  phone_number text,
  metadata jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reelplex_notification_state (
  content_type text primary key check (content_type in ('movie', 'series')),
  last_content_id text not null,
  last_content_title text,
  last_vj text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists subscriptions_status_idx on public.subscriptions(status);
create index if not exists subscriptions_expiry_idx on public.subscriptions(expiry_date);
create index if not exists profiles_subscription_idx on public.profiles(subscription);
create index if not exists profiles_trial_status_idx on public.profiles(trial_status);
create index if not exists transactions_status_idx on public.transactions(status);
create index if not exists transactions_provider_tx_idx on public.transactions(provider_transaction_id);
create index if not exists reelplex_notification_state_updated_at_idx on public.reelplex_notification_state(updated_at desc);

alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.transactions enable row level security;
alter table public.reelplex_notification_state enable row level security;

create policy "admins can manage reelplex notification state" on public.reelplex_notification_state for all to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Idempotent payment webhook storage.
-- Idempotency uses the existing provider_transaction_id/reference fields.
create unique index if not exists transactions_provider_tx_unique_idx on public.transactions(provider_transaction_id) where provider_transaction_id is not null;
