-- Kilax application tables. Run this in Supabase SQL editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  plan text not null,
  start_date date not null,
  end_date date not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  reference uuid unique,
  status text,
  amount numeric,
  currency text,
  provider text,
  provider_transaction_id text,
  phone_number text,
  metadata jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists transactions_status_idx on public.transactions(status);
create index if not exists transactions_provider_tx_idx on public.transactions(provider_transaction_id);

alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.transactions enable row level security;

-- Idempotent payment webhook storage.
-- Idempotency uses the existing provider_transaction_id/reference fields.
create unique index if not exists transactions_provider_tx_unique_idx on public.transactions(provider_transaction_id) where provider_transaction_id is not null;
