create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  target_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs(created_at desc);
create index if not exists admin_audit_logs_admin_user_id_idx on public.admin_audit_logs(admin_user_id);
alter table public.admin_audit_logs enable row level security;
create policy "admins can read audit logs" on public.admin_audit_logs for select to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins can insert audit logs" on public.admin_audit_logs for insert to authenticated with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
